### PR TITLE
Update Portuguese translations

### PR DESCRIPTION
**Pull request by DavidoAprendiz**
Hello!
The motivation for this PR is to update 'PT' translation.

This isn't the best benchmark since languages can change drastically between them, but... :)

- The English translation file currently has 240 lines.

Before -> 168 lines
After  -> 240 lines

Files Changed:
- index.json
  -> Remove duplicated line.  
  -> Update (old) nickname.
- Lang_pt.properties
  -> Add missing fields.

### CODE REVIEW

**Comment by satsen** [comment]
Thanks for the update.
Those lines that were commented out (those that begun with #) were made so because the term "mnemonic phrase" was changed to "seed phrase" everywhere in the program as it is the better term for describing it. However if that is how it is in your language you can keep the old translation but I suggest to change it to reflect the new base string

**Comment by satsen** [comment]
Also these strings:

- `extendedSeedPassphrase=Frase-mnemónica alargada`
- `copyExtendedPassphrase=Copiar frase-mnemónica alargada`

Might be incorrectly translated. The extended seed passphrase string is not part of the seed phrase, it is a separate passphrase that is used along with the seed phrase. Of course, I might be judging incorrectly here so if it is correct then disregard this comment.

**Comment by DavidoAprendiz** [comment]
Thank you for your feedback! I completely understand your view, I personally only use this expression in English. 
The direct translation for seed-phrase would be "frase-semente" but this isn't used in Portuguese at all (Portugal).
In Brazil, the word "mnemônica" is written only with a different accent mark, but with a quick search I can see the expression "frase-semente" used very frequently...  
  - Portugal dict (with Brazil too at the bottom) -> https://dicionario.priberam.org/mnem%C3%B3nica 
  - Brazil example ->  https://www.ledger.com/pt-br/como-proteger-sua-frase-semente

Yes, you're completely right. I've changed those fields to better describe them! 
The direct translation would be something like "palavra-frase da semente" but again this isn't used in Portugal... :) 
I changed to "palavra-passe da frase-mnemónica".
 
Please let me know if something needs to be changed! 
If you want, I can change these expressions to have a "Brazilian style" :)
Thank you!

**Comment by satsen** [comment]
Hey, seems like I forgot to reply. The current translations are good.

I just added some more strings, can you translate them as well? Thank you. This is the last time I'm adding strings before the next version.

**Comment by satsen** [comment]
If you want to translate the new strings, please make a new pull request. Thank you for your contribution.

**Pull request merged**
