### PR TITLE
Compile on GHA

### PR DESCRIPTION
**Pull request by MrStahlfelge**

### CODE REVIEW

**Comment by satsen** [comment]
Oh I just noticed this

**Comment by satsen** [comment]
I don't think the build task does what's needed. The build-all-runtimes.sh script should be executed

**Comment by satsen** [comment]
Or if Github Actions has some specific feature for this, the runtimeZip should be run with -Pplatform=<platform> for all platforms (win linux linux-aarch64 linux-arm32 mac mac-aarch64) in a list or loop or whatever

**Comment by MrStahlfelge** [comment]
It's not a release, it's a compile check on every commit.

**Comment by satsen** [comment]
But what's the purpose then, to verify that pull requests compile?

**Pull request merged**
